Add AutoUpgrade for cChocoPackageInstallerSet
PowerShellOrg/cChoco pull request #108
Opened 2018-04-19 16:32 UTC by JustinGrote

Allow for auto-upgrade to be used with installerset as well

2018-10-10 04:16 UTC, pauby commented
@JustinGrote Is there an issue related to this? If not can you raise one?

2018-10-10 06:30 UTC, JustinGrote commented
Not sure if I did an issue, I'll prepare.

2018-12-07 20:57 UTC, jrdnr commented
@pauby This PR addresses #80

2018-12-12 10:33 UTC, pauby requested changes
This is a relatively straghtforward change. Once the minor issues are addressed I'm happy to merge.

2018-12-12 10:33 UTC, pauby commented on DSCResources/cChocoPackageInstallerSet/cChocoPackageInstallerSet.schema.psm1
> +        [ValidateNotNullOrEmpty()]
A boolean can only have $true or $false. If you pass anything empty it won't convert and will throw an (conversion) exception. So this is effectively redundant.

2018-12-12 10:33 UTC, pauby commented on DSCResources/cChocoPackageInstallerSet/cChocoPackageInstallerSet.schema.psm1
> +        [bool]
To keep with the rest of the data types in the parameter declaration can you use [System.Boolean]?

2019-07-28 14:40 UTC, pauby commented
As the original source repo for this is now gone I'm going to go ahead and close it.

2019-07-28 14:40 UTC, closed without merging