Add test-path handler to cChocoPackageInstall in case of missing ChocoInstalled.xml
PowerShellOrg/cChoco pull request #177
Opened 2023-06-12 15:07 UTC by BCOps

## Description Of Changes
`cChocoPackageInstall` `Get-ChocoInstalledPackage` has been updated to test for the presence of `ChocoInstalled.xml` before trying to delete it when purge is set to true, avoiding a breaking error if it is not located.

## Motivation and Context
Fixes #160 

## Testing
1. Validated on Windows Server 2019 by creating local cChoco DSC module at new version with applied changes. Resource specified was uninstalled and reinstalled at specific verison (as per report in issue #160 ) with graceful handling of the missing ChocoInstalled.xml file. File was not detected, `remove-item` was skipped, and module run completed successfully.
### Operating Systems Testing
- Windows Server 2019 Core
- Windows Server 2016

## Change Types Made

* [x] Bug fix (non-breaking change).
* [ ] Feature / Enhancement (non-breaking change).
* [ ] Breaking change (fix or feature that could cause existing functionality to change).
* [ ] Documentation changes.
* [x] PowerShell code changes.

## Change Checklist

* [ ] Requires a change to the documentation.
* [ ] Documentation has been updated.
* [ ] Tests to cover my changes, have been added.
* [x] All new and existing tests passed?
* [x] PowerShell code changes: PowerShell v2 compatibility checked?

## Related Issue
Fixes #160

2023-06-12 15:19 UTC, BCOps commented
Appveyor tests are showing as [passing](https://ci.appveyor.com/project/chocolatey/cchoco/builds/47283025)

2023-07-06 20:29 UTC, corbob requested changes
In general this code looks good. I would like to potentially see the commits updated to follow the Chocolatey guidelines, but we don't currently have anything on this repository to indicate the style and such, so for now I'll leave that.

I would however prefer to see some pester tests that test this issue if possible. However, it would be good to look at Pester 5 tests as #163 is adding that support. If you wanted to take a look at adding some after that is merged it'd be appreciated.

2023-07-06 20:48 UTC, corbob commented
I just had a bit of a perusal over #103. If I understand this PR correctly, I suspect it took inspiration from that PR? Instead of the `Invoke-Chocolatey` and `Invoke-ChocolateyProcess`, we might want to consider using `Invoke-Choco` from the Chocolatey Pester tests [here](https://github.com/chocolatey/choco/blob/develop/tests/helpers/common/Chocolatey/Invoke-Choco.ps1). Although maybe not returning or logging as much as there as it's not likely needed in the DSC context.

2024-02-12 08:50 UTC, AF250329 commented
Is there any news about this Pull Request ? Is it gonna be merged ?

2024-02-13 13:03 UTC, pauby commented
@AF250329 This PR is waiting on a response to the last comment by @corbob.

2024-02-13 13:23 UTC, closed without merging